#%RAML 1.0
title: A CRUD API for Users and Groups

uses:
  example: annotations.1_0.yaml

/things:
  description: All the users
  get:
    responses:
      200:
        body:
          application/json:
            examples: !include examples.yaml  
